### ISSUE TITLE
Swift Package Versioning

### ISSUE THREAD

**Issue by Sam-Spencer** [Cindori/FluidGradient#3]
Absolutely lovely work here; can't wait to pull it into a project. Would make things just a tad easier if there were tagged releases so SPM can target a range of versions (instead of just the `main` branch). Just a nice to have when you get chance!

Thanks again! Cheers 🥂 !

**Comment by joogps** [comment]
Hey @Sam-Spencer, did just that!

Turns out I completely missed this step when working on the articles :)

Thanks for the reminder!
