### ISSUE TITLE
Is any analogue for Android?

### ISSUE THREAD

**Issue by nurshark** [Cindori/FluidGradient#5]

**Comment by joogps** [comment]
Hi, @nurshark!

Thank you for your interest! As a Swift Package built with native Apple frameworks, this project is not available for Android development.

You could find similar projects for Android apps online. For example, I found this [Dart package](https://pub.dev/packages/mesh_gradient) for Flutter that seems to implement something along the lines of this repo.

I'm sure you can find something good and proper for your stack. Have fun coding! 🍀
